"""email verification

Revision ID: 8d4cd3fda368
Revises: b2c3d4e5f6a7
Create Date: 2026-04-15 19:11:02.208180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4cd3fda368'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
