"""descricao do que mudou

Revision ID: bb53f290c54a
Revises: b70e10b25954
Create Date: 2026-03-30 22:08:55.207451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb53f290c54a'
down_revision = 'b70e10b25954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_bill_transaction', 'transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bill_transaction', type_='foreignkey')

    # ### end Alembic commands ###
